name: trade_thrust
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts:
  material_design_icons_flutter:
  flutter_launcher_icons:

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/img.png


flutter_icons:
  image_path: "assets/icon/img.png"
  android: true
  ios: true
